# Use the official Node.js image as the base  
# FROM node:20.11.0  

FROM alpine:3.20

RUN apk update
RUN apk add nodejs npm


# # Set the working directory inside the container  
WORKDIR /sfgov  

# # Copy the app source code to the container  
COPY . .  

# # Install dependencies  
RUN npm install
# RUN npm install storybook

# # Build the Next.js app  
# RUN npm run build  

# Expose the port the app will run on  
# EXPOSE 3000  

# Start the app  
CMD ["npm", "start"] 