terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-1"
}

provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

locals {
  common_tags = {
    ProductTeam      = "cms"
    ManagedBy        = "terraform"
    Repository       = "sfgov-next"
    Namespace        = "cms"
    awsApplication   = "arn:aws:resource-groups:us-west-1:395833734759:group/cms/0c2c9s2swv2wroqlpkj2vakld5"
  }
}

# Data sources for ALB (shared resource at root level)
data "aws_subnet" "loadbalancers_b" {
  id = "subnet-0e8ca1ae723d17550"
}

data "aws_subnet" "loadbalancers_c" {
  id = "subnet-0af5858b570b99beb"
}

data "aws_security_group" "platform_cf_ec2_web" {
  id = "sg-0ea54c21fd6940771"
}

data "aws_security_group" "cms_cf_alb_web" {
  id = "sg-0abc71626ad3557d7"
}

module "cms_training" {
  source = "./modules/cms"

  providers = {
    aws.us-east-1 = aws.us-east-1
  }

  environment            = "training"
  cluster_arn            = aws_ecs_cluster.cms_common.arn
  api_base_url           = "https://api-training.dev.sf.gov"
  listener_arn           = "arn:aws:elasticloadbalancing:us-west-1:395833734759:listener/app/cms-common/b8f665a290342dce/ea41240ac8c9d2f3"
  listener_rule_priority = 10
  host_header            = "web-training-ecs.dev.sf.gov"
  alb_dns_name           = aws_lb.cms_common.dns_name
  container_image        = "395833734759.dkr.ecr.us-west-1.amazonaws.com/platform/web:training-ecs"

  # vpc_id, subnets, security_groups, alb_security_groups, route53_zone_id,
  # task_role_arn, execution_role_arn, and acm_certificate_arn
  # are now auto-discovered/generated by the module

  task_cpu      = "1024"
  task_memory   = "2048"
  desired_count = 1

  common_tags = local.common_tags
}

resource "aws_ecs_cluster" "cms_common" {
  name = "cms-common"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = merge(local.common_tags, {
    Name = "cms-common"
  })
}

resource "aws_lb" "cms_common" {
  name               = "cms-common"
  internal           = false
  load_balancer_type = "application"
  security_groups = [
    data.aws_security_group.platform_cf_ec2_web.id,
    data.aws_security_group.cms_cf_alb_web.id
  ]
  subnets = [data.aws_subnet.loadbalancers_b.id, data.aws_subnet.loadbalancers_c.id]

  ip_address_type = "ipv4"

  access_logs {
    enabled = true
    bucket  = "aws-control-tower-elb-local-logs-395833734759-us-west-1"
    prefix  = "cms-common"
  }

  tags = merge(local.common_tags, {
    Name = "cms-common"
  })
}
