terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-1"
}

provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

locals {
  common_tags = {
    ProductTeam      = "cms"
    ManagedBy        = "terraform"
    Repository       = "sfgov-next"
    Namespace        = "cms"
    awsApplication   = "arn:aws:resource-groups:us-west-1:395833734759:group/cms/0c2c9s2swv2wroqlpkj2vakld5"
  }
}

# Data sources for ALB (shared resource at root level)
data "aws_subnet" "loadbalancers_b" {
  id = "subnet-0e8ca1ae723d17550"
}

data "aws_subnet" "loadbalancers_c" {
  id = "subnet-0af5858b570b99beb"
}

data "aws_security_group" "platform_cf_ec2_web" {
  id = "sg-0ea54c21fd6940771"
}

data "aws_security_group" "cms_cf_alb_web" {
  id = "sg-0abc71626ad3557d7"
}

module "cms_training" {
  source = "./modules/cms"

  providers = {
    aws.us-east-1 = aws.us-east-1
  }

  environment  = "training"
  cluster_arn  = aws_ecs_cluster.cms_common.arn
  web_base_url = "https://web-training-ecs.dev.sf.gov"
  api_base_url = "https://api-training-ecs.dev.sf.gov"
  listener_arn = "arn:aws:elasticloadbalancing:us-west-1:395833734759:listener/app/cms-common/b8f665a290342dce/42180e862fbd03e6"
  alb_dns_name = aws_lb.cms_common.dns_name
  alb_zone_id  = aws_lb.cms_common.zone_id

  # vpc_id, subnets, security_groups, alb_security_groups, route53_zone_id,
  # task_role_arn, execution_role_arn, and acm_certificate_arn
  # are now auto-discovered/generated by the module

  # Web service configuration
  web_container_image        = "395833734759.dkr.ecr.us-west-1.amazonaws.com/platform/web:training"
  web_task_cpu               = "1024"
  web_task_memory            = "2048"
  web_desired_count          = 1
  web_listener_rule_priority = 10
  # web_host_header defaults to "web-training-ecs.dev.sf.gov" (extracted from web_base_url)

  # API/Wagtail service configuration
  api_container_image        = "395833734759.dkr.ecr.us-west-1.amazonaws.com/platform/api:ef_test"
  api_task_cpu               = "1024"
  api_task_memory            = "2048"
  api_desired_count          = 1
  api_listener_rule_priority = 20
  api_secrets_arn            = "arn:aws:secretsmanager:us-west-1:395833734759:secret:sfgov-training-api-xn8NYL"
  api_db_host                = "platform-training-db.cfjeqzrktdjf.us-west-1.rds.amazonaws.com"
  api_db_name                = "platform_platform"
  api_db_port                = "5432"
  # api_host_header defaults to "api-training.dev.sf.gov" (extracted from api_base_url)

  common_tags = local.common_tags
}

resource "aws_ecs_cluster" "cms_common" {
  name = "cms-common"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  configuration {
    execute_command_configuration {
      logging = "DEFAULT"
    }
  }

  tags = merge(local.common_tags, {
    Name = "cms-common"
  })
}

resource "aws_lb" "cms_common" {
  name               = "cms-common"
  internal           = false
  load_balancer_type = "application"
  security_groups = [
    data.aws_security_group.platform_cf_ec2_web.id,
    data.aws_security_group.cms_cf_alb_web.id
  ]
  subnets = [data.aws_subnet.loadbalancers_b.id, data.aws_subnet.loadbalancers_c.id]

  ip_address_type = "ipv4"

  access_logs {
    enabled = true
    bucket  = "aws-control-tower-elb-local-logs-395833734759-us-west-1"
    prefix  = "cms-common"
  }

  tags = merge(local.common_tags, {
    Name         = "cms-common"
    map-migrated = "mig2JADMTOT5G"
  })
}
