version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.4.0

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image:
          repo: 395833734759.dkr.ecr.us-west-1.amazonaws.com/sfgov-next
          tag: "${CIRCLE_SHA1}"