version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.4.0
  aws-cli: circleci/aws-cli@5.2.0

workflows:
    example-workflow:
      jobs:
        - aws-ecr/build_and_push_image:
            auth: 
              - aws-cli/setup:
                auth: static
                aws_access_key_id: "${$AWS_ACCESS_KEY_ID}"
                aws_secret_access_key: "${$AWS_SECRET_ACCESS_KEY}"
            repo: "sfgov-next"
            account_id: "395833734759"
            aws_domain: "amazonaws.com"
            region: "us-west-1"
            tag: "${CIRCLE_SHA1}, latest"
