import { classed, HeadingMd, HeadingSm, HeadingXl, Link } from '@/design-system'
import { RichText as WagtailRichText } from './wagtail'
import { Image } from './Image'

import type { HTMLComponentMap } from './wagtail'

type RichTextProps = {
  html: string
  components?: HTMLComponentMap
}

export function getTocId(blockKey?: string) {
  return blockKey ?? Math.floor(Math.random() * 200)
}

// h2 and h3 get an extra data-block-key type for table of contents
// which is generated by wagtail's rich text converter
export const RICH_TEXT_DEFAULT_COMPONENTS = {
  h2: ({
    'data-block-key': blockKey,
    ...rest
  }: JSX.IntrinsicElements['h2'] & { 'data-block-key'?: string }) => (
    <HeadingXl as="h2" id={getTocId(blockKey)} {...rest} />
  ),
  h3: ({
    'data-block-key': blockKey,
    ...rest
  }: JSX.IntrinsicElements['h3'] & { 'data-block-key'?: string }) => (
    <HeadingMd as="h3" id={getTocId(blockKey)} {...rest} />
  ),
  h4: (props) => <HeadingSm as="h4" {...props} />,
  a: (props) => <Link as="a" className="text-primary600" {...props} />,
  p: classed('p', 'mb-16'),
  br: () => <br data-testid="test-br" />,
  hr: classed('div', 'border-dotted border-b-2 w-full border-neutral200'),
  img: Image,
  blockquote: classed('blockquote', 'bg-neutral50 p-20 rounded-4')
} as const satisfies HTMLComponentMap

export const RichText = ({ html, components }: RichTextProps) => {
  const mergedComponentMap = {
    ...RICH_TEXT_DEFAULT_COMPONENTS,
    ...components
  }

  return <WagtailRichText html={html} components={mergedComponentMap} />
}
