/* istanbul ignore file */

export const ABOUT_PAGE_TYPE = 'sf.About'
export const AGENCY_PAGE_TYPE = 'sf.Agency'
export const CAMPAIGN_PAGE_TYPE = 'sf.Campaign'
export const DATA_STORY_PAGE_TYPE = 'sf.DataStory'
export const EVENT_PAGE_TYPE = 'sf.Event'
export const INFO_PAGE_TYPE = 'sf.Information'
export const LOCATION_PAGE_TYPE = 'sf.LocationPage'
export const MEETING_PAGE_TYPE = 'sf.Meeting'
export const NEWS_PAGE_TYPE = 'sf.News'
export const PROFILE_PAGE_TYPE = 'sf.Profile'
export const REPORT_PAGE_TYPE = 'sf.Report'
export const STEP_BY_STEP_PAGE_TYPE = 'sf.StepByStep'
export const TOPIC_PAGE_TYPE = 'sf.Topic'
export const TRANSACTION_PAGE_TYPE = 'sf.Transaction'
export const WAGTAIL_IMAGE_TYPE = 'wagtailimages.Image'
export const WAGTAIL_DOCUMENT_TYPE = 'wagtaildocs.Docment'
