name: QA sites teardown
on:
  pull_request:
    types:
      - closed

jobs:
  on-pr-closed:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3
    steps:
      - name: install ansible tower cli
        run: |
          if [ "${{ vars.QA_TEARDOWN_JOB_ID }}" != "" ]; then
            apt-get update && apt-get install -y vim
            pip install --root-user-action=ignore ansible-tower-cli
          fi
      - name: teardown qa site instance via tower-cli
        run: |
          if [ "${{ vars.QA_TEARDOWN_JOB_ID }}" != "" ]; then
            export TOWER_HOST=${{ vars.AWX_HOST }}
            export TOWER_OAUTH_TOKEN=${{ secrets.AWX_ACCESS_TOKEN }}
            export TOWER_VERBOSE=true
            tower-cli job launch --job-template=${{ vars.QA_TEARDOWN_JOB_ID }} --extra-vars="prbranch=${{ github.event.number }}" --wait
          fi
